### ISSUE TITLE
exception "req.abort is not a function"

### ISSUE THREAD

**Issue by rg-engineering** [iobroker-community-adapters/ioBroker.philips-air#12]
Adapter does not run anymore at all.
Getting exceptions:

```
host.ioBrokerHost | 2021-09-24 10:48:34.544 | error | Caught by controller[0]: Error by sending: Error: No reply in 247s
philips-air.0 | 2021-09-24 10:48:33.934 | error | req.abort is not a function
philips-air.0 | 2021-09-24 10:48:33.933 | error | TypeError:  req.abort is not a function    at OutgoingMessage.<anonymous>  (/opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:118:21)     at OutgoingMessage.emit (events.js:314:20)    at RetrySend.emit  (events.js:314:20)    at Timeout._onTimeout  (/opt/iobroker/node_modules/coap/lib/retry_send.js:77:12)    at  listOnTimeout (internal/timers.js:554:17)    at processTimers  (internal/timers.js:497:7)
philips-air.0 | 2021-09-24 10:48:33.930 | error | uncaught exception: req.abort is not a function
host.ioBrokerHost | 2021-09-24 10:43:55.053 | error | instance system.adapter.philips-air.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBrokerHost | 2021-09-24 10:43:55.052 | error | Caught by controller[0]: Error by sending: Error: No reply in 247s
philips-air.0 | 2021-09-24 10:43:54.444 | error | req.abort is not a function
philips-air.0 | 2021-09-24 10:43:54.442 | error | TypeError:  req.abort is not a function    at OutgoingMessage.<anonymous>  (/opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:118:21)     at OutgoingMessage.emit (events.js:314:20)    at RetrySend.emit  (events.js:314:20)    at Timeout._onTimeout  (/opt/iobroker/node_modules/coap/lib/retry_send.js:77:12)    at  listOnTimeout (internal/timers.js:554:17)    at processTimers  (internal/timers.js:497:7)
philips-air.0 | 2021-09-24 10:43:54.439 | error | uncaught exception: req.abort is not a function
host.ioBrokerHost | 2021-09-24 10:39:15.817 | error | instance system.adapter.philips-air.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBrokerHost | 2021-09-24 10:39:15.814 | error | Caught by controller[0]: Error by sending: Error: No reply in 247s
philips-air.0 | 2021-09-24 10:39:15.194 | error | req.abort is not a function
philips-air.0 | 2021-09-24 10:39:15.193 | error | TypeError:  req.abort is not a function    at OutgoingMessage.<anonymous>  (/opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:118:21)     at OutgoingMessage.emit (events.js:314:20)    at RetrySend.emit  (events.js:314:20)    at Timeout._onTimeout  (/opt/iobroker/node_modules/coap/lib/retry_send.js:77:12)    at  listOnTimeout (internal/timers.js:554:17)    at processTimers  (internal/timers.js:497:7)
philips-air.0 | 2021-09-24 10:39:15.189 | error | uncaught exception: req.abort is not a function
```

**Comment by Apollon77** [comment]
Which nodejs version?  What was dne before it did nor work anymore? maybe a Nodejs upgrade?

**Comment by rg-engineering** [comment]
it was working for while. Only possible change is a connection lost (WLAN disconnection). Nothing else changed...
Adapter was suddenly red in admin...

nodejs: 12.22.4

**Comment by rg-engineering** [comment]
now a log in debug mode:

```
philips-air.0 | 2021-09-24 12:53:23.566 | info | starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.philips-air, node: v12.22.4, js-controller: 3.3.15
-- | -- | -- | --
philips-air.0 | 2021-09-24 12:52:51.364 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
philips-air.0 | 2021-09-24 12:52:51.363 | info | terminating
philips-air.0 | 2021-09-24 12:52:51.356 | error | req.abort is not a function
philips-air.0 | 2021-09-24 12:52:51.355 | error | TypeError: req.abort is not a function     at OutgoingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:118:21)     at OutgoingMessage.emit (events.js:314:20)     at RetrySend.emit (events.js:314:20)     at Timeout._onTimeout (/opt/iobroker/node_modules/coap/lib/retry_send.js:77:12)     at listOnTimeout (internal/timers.js:554:17)     at processTimers (internal/timers.js:497:7)
philips-air.0 | 2021-09-24 12:52:51.353 | error | uncaught exception: req.abort is not a function
philips-air.0 | 2021-09-24 12:48:44.218 | info | starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.philips-air, node: v12.22.4, js-controller: 3.3.15
philips-air.0 | 2021-09-24 12:48:43.625 | debug | statesDB connected
philips-air.0 | 2021-09-24 12:48:43.624 | debug | States connected to redis: 0.0.0.0:9000
philips-air.0 | 2021-09-24 12:48:43.393 | debug | States create User PubSub Client
philips-air.0 | 2021-09-24 12:48:43.391 | debug | States create System PubSub Client
philips-air.0 | 2021-09-24 12:48:43.380 | debug | Redis States: Use Redis connection: 0.0.0.0:9000
philips-air.0 | 2021-09-24 12:48:43.378 | debug | objectDB connected
philips-air.0 | 2021-09-24 12:48:43.370 | debug | Objects connected to redis: 0.0.0.0:9001
philips-air.0 | 2021-09-24 12:48:43.345 | debug | Objects client initialize lua scripts
philips-air.0 | 2021-09-24 12:48:43.343 | debug | Objects create User PubSub Client
philips-air.0 | 2021-09-24 12:48:43.342 | debug | Objects create System PubSub Client
philips-air.0 | 2021-09-24 12:48:43.340 | debug | Objects client ready ... initialize now
philips-air.0 | 2021-09-24 12:48:43.304 | debug | Redis Objects: Use Redis connection: 0.0.0.0:9001
philips-air.0 | 2021-09-24 10:48:33.934 | error | req.abort is not a function
philips-air.0 | 2021-09-24 10:48:33.933 | error | TypeError:  req.abort is not a function    at OutgoingMessage.<anonymous>  (/opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:118:21)     at OutgoingMessage.emit (events.js:314:20)    at RetrySend.emit  (events.js:314:20)    at Timeout._onTimeout  (/opt/iobroker/node_modules/coap/lib/retry_send.js:77:12)    at  listOnTimeout (internal/timers.js:554:17)    at processTimers  (internal/timers.js:497:7)
philips-air.0 | 2021-09-24 10:48:33.930 | error | uncaught exception: req.abort is not a function

```

**Comment by rg-engineering** [comment]
The problem arises when there is an unstable WiFi connection. In my case a repeater had failed. The ping on the device was answered, the app also worked. Apparently the WLAN connection was not stable and reliable enough to address the device from the adapter. The exception comes when a connection retry is to be carried out after a timeout. A corresponding error message would be helpful here ...

**Comment by Apollon77** [comment]
@rg-engineering DO you want to provide an PR?

**Comment by rg-engineering** [comment]
@Apollon77  yes, please see here:  https://github.com/iobroker-community-adapters/ioBroker.philips-air/pull/13
